### ISSUE TITLE
aelf-command - create nft token

### ISSUE THREAD

**Issue by AbigailDeng** [AElfProject/aelf-command#85]
### Description
Create multiple NFT tokens simultaneously

### Tasks
- [x] discussion https://aelfblockchain.sg.larksuite.com/wiki/YPEBwuC1BibtH5kX0M4lwoCvgAb
- [x] Complete the entire process of creating NFT tokens.
- [x] Write a command to create multiple NFT tokens.
